const products = [
  {
    id: 1,
    name: " LD01 LOUNGE CHAIR",
    profit: 950.19,
    price: 13.04,
    image: "./images/1.png",
    description:
      "Expertly rendered by Carl Hansen & Søn, the lounge chair—first introduced in 1951 and enduring ever since—is available in oak or as a combination of oak and walnut, sourced from sustainable forestry. Choose from seat and back upholstery in a selection of leather options or in a custom fabric.",
  },
  {
    id: 2,
    name: " OKM BIONIC X4 LONG RANGE GOLD METAL DETECTOR",
    profit: 910.19,
    price: 12.14,
    image: "./images/001_Bx4-346x385.png",
    description:
      "The Bionic X4 long-range gold detector has been developed especially for gold seekers, gold prospectors and treasure hunters, who look for gold at far distances. Unlike traditional long-range detectors, the Bionic X4 can be combined with an Android Smartphone to visually locate gold targets.",
  },
  {
    id: 3,
    name: "Vacheron hotsell constantin cross",
    profit: 2170.32,
    price: 23.54,
    image: "./images/watch.png",
    description: "Vacheron hotsell constantin cross",
  },
  {
    id: 4,
    name: "BITMAIN ANTMINER D7 1286GH",
    profit: 1560.49,
    price: 21.94,
    image: "./images/d72.png",
    description:
      "he Antminer D7 is a X11 algorithm ASIC miner produced by Bitmain. It produces 1286GH/s and has a power consumption of 3148W. This model is currently the most powerful and efficient X11 miner on the market. You can mine all cryptocurrencies using the same algorithm such as Dash (DASH) and Onix (ONX)",
  },
  {
    id: 5,
    name: "ZOTAC GAMING GEFORCE RTX 4080 SUPER TRINITY BLACK EDITION 16GB GDDR6X",
    profit: 3910.19,
    price: 31.94,
    image: "./images/gef.png",
    description:
      "ZOTAC GAMING GEFORCE RTX 4080 SUPER TRINITY BLACK EDITION 16GB GDDR6X",
  },
  {
    id: 6,
    name: "VAGKRI 24 Inch Industrial Drum Fan, 320W High Velocity Floor Fan",
    profit: 4530.46,
    price: 42.51,
    image: "./images/fan.png",
    description:
      "VAGKRI 24 Inch Industrial Drum Fan, 320W High Velocity Floor Fan",
  },
  {
    id: 7,
    name: "APPLE IPAD 2 WI-FI+3G 64GB",
    profit: 1220.31,
    price: 19.04,
    image: "./images/Apple.png",
    description: "APPLE IPAD 2 WI-FI+3G 64GB",
  },
  {
    id: 8,
    name: "GALAXY Z FOLD 512GB",
    profit: 1630.09,
    price: 22.49,
    image: "./images/product6.png",
    description: "GALAXY Z FOLD 512GB",
  },
  {
    id: 9,
    name: "APPLE SERIES 5 WATCH 8TH GEN",
    profit: 810.19,
    price: 16.34,
    image: "./images/product8.png",
    description: "APPLE SERIES 5 WATCH 8TH GEN",
  },
  {
    id: 10,
    name: " LD04 LOUNGE CHAIR",
    profit: 990.26,
    price: 19.99,
    image: "./images/4.png",
    description:
      "Expertly rendered by Carl Hansen & Søn, the lounge chair—first introduced in 1951 and enduring ever since—is available in oak or as a combination of oak and walnut, sourced from sustainable forestry. Choose from seat and back upholstery in a selection of leather options or in a custom fabric.",
  },
  {
    id: 11,
    name: "NOKON CAMERA",
    profit: 1452.19,
    price: 23.01,
    image: "./images/ikon.png",
    description: "NOKON CAMERA",
  },
  {
    id: 12,
    name: "2024 Surron Light Bee X Electric Bike",
    profit: 9810.19,
    price: 96.94,
    image: "./images/bike4.png",
    description: "2024 Surron Light Bee X Electric Bike",
  },
  {
    id: 13,
    name: "Wulling Electric EV Car",
    profit: 11410.09,
    price: 132.74,
    image: "./images/car1.png",
    description: "Wulling Electric EV Car",
  },
  {
    id: 14,
    name: "10.0kW ENVIROMAX10 Industrial Portable Air Conditioner",
    profit: 5735.54,
    price: 63.51,
    image: "./images/air.png",
    description: "i10.0kW ENVIROMAX10 Industrial Portable Air Conditioner",
  },
  {
    id: 15,
    name: "RFM Electric EV Car",
    profit: 10810.19,
    price: 118.94,
    image: "./images/car2.png",
    description: "RFM Electric EV Car",
  },
  {
    id: 16,
    name: "Roland SPD SX Octopad total percussion 🥁 Drum",
    profit: 1041.19,
    price: 16.32,
    image: "./images/DRUM.png",
    description: "Roland SPD SX Octopad total percussion 🥁 Drum",
  },
  {
    id: 17,
    name: " LD06 LOUNGE CHAIR",
    profit: 724.06,
    price: 12.64,
    image: "./images/6.png",
    description:
      "Expertly rendered by Carl Hansen & Søn, the lounge chair—first introduced in 1951 and enduring ever since—is available in oak or as a combination of oak and walnut, sourced from sustainable forestry. Choose from seat and back upholstery in a selection of leather options or in a custom fabric.",
  },
  {
    id: 18,
    name: "PASSIONATE SONIA CAMERA 4GB 5MP3",
    profit: 2910.19,
    price: 31.04,
    image: "./images/isg.png",
    description: "PASSIONATE SONIA CAMERA 4GB 5MP3",
  },
  {
    id: 19,
    name: "RAZER BLADE 15'6INCH FHD GAMING LAPTOP",
    profit: 3490.19,
    price: 39.94,
    image: "./images/LAP.png",
    description: "RAZER BLADE 15'6INCH FHD GAMING LAPTOP",
  },
  {
    id: 20,
    name: "Nike SB Dunk High",
    profit: 1220.48,
    price: 19.37,
    image: "./images/nike.png",
    description: "Nike SB Dunk High",
  },
  {
    id: 21,
    name: "Janome MB-7 MB7 7 Needle Embroidery Machine Plus Deluxe Bonus Kit",
    profit: 4010.19,
    price: 42.24,
    image: "./images/ship.png",
    description:
      "Janome MB-7 MB7 7 Needle Embroidery Machine Plus Deluxe Bonus Kit",
  },
  {
    id: 22,
    name: "IPHONE 16 PROMAX 256 GB DUAL SIM DESERT TITANIUM",
    profit: 2993.19,
    price: 27.74,
    image: "./images/iphone.png",
    description: "IPHONE 16 PROMAX 256 GB DUAL SIM DESERT TITANIUM",
  },
  {
    id: 23,
    name: "Sony 55” Bravia 8 4K Ultra HD OLED Smart TV (FWD55XR80)",
    profit: 910.19,
    price: 11.04,
    image: "./images/tv.png",
    description: "Sony 55” Bravia 8 4K Ultra HD OLED Smart TV (FWD55XR80)",
  },
  {
    id: 24,
    name: "GEMSY 7724E Overlocker Direct Drive Industrial Sewing Machine.",
    profit: 6748.52,
    price: 53.29,
    image: "./images/sew.png",
    description:
      "GEMSY 7724E Overlocker Direct Drive Industrial Sewing Machine.",
  },
];
export default products;
